[project]
name = "battery-test-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gitpython>=3.1.45",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "openpyxl>=3.1.5",
    "pyinstaller>=6.15.0",
    "pyqt5>=5.15.9",
    "pyqt5-tools>=5.15.9.3.3",
    "python-docx>=1.2.0",
    "pywin32>=311",
    "xlrd==1.2.0",
    "xlsxwriter~=3.0.8",
]
